vich_uploader:
    db_driver: orm

    mappings:
        flash_file:
            # alias qui nous permet d'accéder à nos images depuis le navigateur
            uri_prefix: /assets/flashs
            # Chemin vers le dossier de stockage
            upload_destination: '%kernel.project_dir%/public/assets/flashs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
        category_file:
            # alias qui nous permet d'accéder à nos images depuis le navigateur
            uri_prefix: /assets/flashs
            # Chemin vers le dossier de stockage
            upload_destination: '%kernel.project_dir%/public/assets/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false