vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        flash_file:
            # alias qui nous permet d'accéder à nos images depuis le navigateur
            uri_prefix: /assets/flash/
            # Chemin vers le dossier de stockage
            upload_destination: '%kernel.project_dir%/public/assets/flash'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
            inject_on_load: true

        category_file:
            # alias qui nous permet d'accéder à nos images depuis le navigateur
            uri_prefix: /assets/flash/
            # Chemin vers le dossier de stockage
            upload_destination: '%kernel.project_dir%/public/assets/flash'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
            inject_on_load: true